
name: Build AW SERVER
on:
  push:
    branches:
      - cicd

jobs:
  build_server:
    runs-on:  [self-hosted, linux]
    name: BUILD AW-SERVER
    environment: auth
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build artifact aw-server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST_AUTH }}
          SERVER_PORT: ${{ secrets.SERVER_PORT_AUTH }}
          DB_HOST: ${{ secrets.DB_HOST_AUTH }}
          DB_PORT: ${{ secrets.DB_PORT_AUTH }}
        run: |
          cd aw_server/
          bash change_config.sh
          cd ../
          bash /home/thiennguyen/miniconda3/etc/profile.d/conda.sh
          conda create -n build-aw-server python=3.8 -y
          conda init bash
          conda activate build-aw-server
          rm -rf poetry.lock
          pip install poetry
          make build
          pip install pymongo waitress
          cd ~/miniconda/envs/build-aw-server/ && zip -r build-aw-server.zip . && cp build-aw-server.zip ~/
          cd ~/ && conda deactivate && conda remove -n build-aw-server --all -y

